apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilab-blue
  namespace: ilab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ilab
      version: blue
  template:
    metadata:
      labels:
        app: ilab
        version: blue
    spec:
      containers:
      - name: ilab
        image: kmgoddard/bgapp:1.3
        ports:
        - containerPort: 80
