apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./deployment/blue
- ./deployment/green
- ./service/
resources:
    - ns.yaml
    - ingresscontrol.yaml
    - ingresscontrolstage.yaml