apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilab-green
  namespace: ilab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ilab
      version: green
  template:
    metadata:
      labels:
        app: ilab
        version: green
    spec:
      containers:
<<<<<<< HEAD
      - name: ilab
        image: kmgoddard/bgapp:1.1
=======
      - name: hotel
        image: kmgoddard/bgapp:1.3
>>>>>>> a9ffb1b8ede502fecc5542f1f59ca700e81af1b8
        ports:
        - containerPort: 80
