apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilab-green
  namespace: ilab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ilab
      version: green
  template:
    metadata:
      labels:
        app: ilab
        version: green
    spec:
       containers:
       - name: ilab
         image: kmgoddard/bgapp:1.4
         ports:
         - containerPort: 80
